from pathlib import Path
from tempfile import TemporaryDirectory
import unittest
import hashlib

from open_radar.publisher import (
    ObservationOnlyPublisher,
    PublisherArtifact,
    PublisherIsolationError,
)
from open_radar.generation import render_readme
from open_radar.storage import ObservationStore


class PublisherTests(unittest.TestCase):
    def test_path_and_content_allowlist(self):
        with TemporaryDirectory() as directory:
            root = Path(directory)
            publisher = ObservationOnlyPublisher(root)
            plan = publisher.plan(
                [
                PublisherArtifact(
                    "data/runs/2026-09.jsonl",
                    '{"schema_version":1,"run_id":"run-1","kind":"collect","started_at":"2026-09-04T00:00:00Z","finished_at":"2026-09-04T00:00:01Z","status":"succeeded","counts":{}}\n',
                    "run",
                ),
                PublisherArtifact(
                    "data/observations/github/2026-09.jsonl",
                    '{"schema_version":1,"record_type":"observation","event_id":"e","collection_key":"slot","run_id":"run-1","project_id":"radar-demo","provider":"github","repository_id":1,"scheduled_at":"2026-09-04T00:00:00Z","observed_at":"2026-09-04T00:00:00Z","recorded_at":"2026-09-04T00:00:00Z","collector_version":"v1","source":"github-api","metrics":{},"facts":{},"unavailable":{}}\n',
                    "observation",
                ),
                    PublisherArtifact("README.md", render_readme([], ObservationStore(root)), "readme"),
                ]
            )
            self.assertEqual(plan.paths[0], "README.md")
            self.assertEqual(
                plan.files[0].sha256,
                hashlib.sha256(plan.files[0].content.encode("utf-8")).hexdigest(),
            )

    def test_protected_paths_and_invalid_content_are_rejected(self):
        publisher = ObservationOnlyPublisher()
        for artifact in (
            PublisherArtifact("data/projects/radar-demo.yaml", "x", "run"),
            PublisherArtifact("data/runs/admission-transactions/2026-09.jsonl", '{}', "run"),
            PublisherArtifact("data/observations/github/../2026-09.jsonl", '{}', "observation"),
            PublisherArtifact("data/observations/github/2026-09.jsonl", "not-json", "observation"),
            PublisherArtifact("README.md", "# no marker", "readme"),
            PublisherArtifact("README.md", "# Open Radar\n<!-- Generated by open-radar; -->", "readme", "0" * 64),
        ):
            with self.assertRaises(PublisherIsolationError):
                publisher.plan([artifact])

    def test_symlink_destination_is_rejected(self):
        with TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "data" / "observations" / "github").mkdir(parents=True)
            (root / "data" / "observations" / "github" / "2026-09.jsonl").symlink_to("/tmp/outside")
            with self.assertRaises(PublisherIsolationError):
                ObservationOnlyPublisher(root).plan([
                    PublisherArtifact("data/observations/github/2026-09.jsonl", '{}', "observation")
                ])


if __name__ == "__main__":
    unittest.main()
